#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: base
  component_name: base
  buttons: [[stop,stop,omni],
    [init,trigger,init],
    [recover,trigger,recover]]
group5:
  group_name: arm_left
  component_name: arm_left
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [home,move,home],
    [folded,move,folded],
    [side, move, side],
    [hug, move, hug],
    [wave, move, wave_hmi],
    [rev_folded(!), move, reverse_folded]]
group6:
  group_name: arm_right
  component_name: arm_right
  buttons: [[stop,stop],
    [init,init],
    [recover,recover],
    [home,move,home],
    [folded,move,folded],
    [side, move, side],
    [hug, move, hug],
    [wave, move, wave_hmi],
    [rev_folded(!), move, reverse_folded]]

